CodeSystem: FRCoreCodeSystemDisciplinePrestation
Id: fr-core-cs-discipline-prestation
Title: "FR Core CodeSystem Discipline de prestation - nomenclature SAE"
Description: "La nomenclature des discipline de prestation."
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablecodesystem"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* ^experimental = false


* #35 "Scanographie X"
* #39 "Radiothérapie externe (césium, cobalt)"
* #43 "Curiethérapie"
* #76 "Immunologie sans autre indication (sai)"
* #102 "Maladies infectieuses"
* #103 "Toxicologie (y compris en particulier activité des centres antipoison)"
* #104 "Réanimation médicale (y compris soins intensifs)"
* #105 "Réanimation polyvalente (médicale + chirurgicale, y compris soins intensifs)"
* #106 "Surveillance continue - médecine (non compris soins intensifs)"
* #107 "Surveillance continue polyvalente (médicale+chirurgicale, non compris soins intensifs)"
* #108 "Pédiatrie indifférenciée"
* #109 "Pédiatrie enfants et adolescents"
* #110 "Pédiatrie nouveau-nés et nourrissons indifférenciée"
* #111 "Pédiatrie nourrissons"
* #112 "Néonatologie"
* #113 "Médecine gériatrique"
* #114 "Spécialités médicales indifférenciées"
* #115 "Allergologie"
* #116 "Dermatologie et vénérologie indifférenciées"
* #117 "Dermatologie"
* #118 "Vénérologie"
* #119 "Endocrinologie, diabétologie, nutrition et métabolisme indifférenciés"
* #120 "Endocrinologie"
* #121 "Diabétologie"
* #122 "Nutrition-métabolisme"
* #123 "Hématologie et maladies du sang"
* #124 "Hépatogastro-entérologie"
* #125 "Maladies tropicales et exotiques"
* #126 "Médecine carcinologique"
* #127 "Médecine cardiovasculaire"
* #129 "Neurologie"
* #130 "Pneumologie indifférenciée"
* #131 "Pneumologie non tuberculeuse"
* #132 "Phtisiologie"
* #133 "Rhumatologie"
* #134 "Radiothérapie et médecine nucléaire indifférenciées"
* #135 "Radiothérapie"
* #136 "Médecine nucléaire"
* #137 "Chirurgie générale"
* #138 "Chirurgie infantile indifférenciée"
* #139 "Chirurgie enfants et adolescents"
* #140 "Chirurgie nouveau-nés et nourrissons"
* #141 "Réanimation chirurgicale indifférenciée (y compris soins intensifs)"
* #142 "Surveillance continue chirurgicale (non compris soins intensifs)"
* #143 "Spécialités chirurgicales indifférenciées"
* #144 "Chirurgie carcinologique"
* #145 "Chirurgie des grands brûlés"
* #146 "Chirurgie digestive"
* #147 "Chirurgie thoracique et cardiovasculaire indiférenciée"
* #148 "Chirurgie thoracopulmonaire"
* #149 "Chirurgie vasculaire"
* #150 "Chirurgie cardiovasculaire"
* #151 "Neurochirurgie"
* #152 "Orthopédie-traumatologie et chirurgie plastique et réparatrice indifférenciées"
* #153 "Orthopédie-traumatologie"
* #154 "Chirurgie plastique et réparatrice"
* #155 "ORL et ophtalmologie indifférenciées"
* #156 "ORL"
* #157 "Ophtalmologie"
* #158 "Stomatologie et chirurgie maxillofaciale indifférenciées"
* #159 "Stomatologie"
* #160 "Chirurgie maxillofaciale"
* #161 "Urologie"
* #162 "ORL, ophtalmologie et stomatologie indifférenciées"
* #163 "Gynécologie et obstétrique indifférenciées"
* #164 "Gynécologie"
* #165 "Obstétrique"
* #166 "Chroniques et convalescents indifférenciés"
* #167 "Chroniques"
* #168 "Repos, convalescence et régime indifférenciés"
* #169 "Repos"
* #170 "Convalescence"
* #171 "Régime (y compris diététique)"
* #172 "Rééducation fonctionnelle et réadaptation polyvalente"
* #173 "Cure thermale indifférenciée"
* #174 "Médecine générale et spécialités médicales indifférenciées"
* #176 "Long séjour pour personnes ayant perdu leur autonomie de vie"
* #177 "Cure médicale en établissement d'hébergements pour personnes âgées"
* #178 "Rééducation fonctionnelle et réadaptation motrice indifférenciée"
* #179 "Rééducation fonctionnelle et réadaptation neurologique"
* #180 "Rééducation des affections respiratoires"
* #181 "Chirurgie générale et spécialités chirugicales indifférenciées"
* #182 "Rééducation des maladies cardiovasculaires"
* #183 "Obstétrique sans possibilités chirurgicales"
* #184 "Rééducation des affections hépatodigestives"
* #185 "Repos et convalescence indifférenciés"
* #187 "Autre rééducation fonctionnelle et réadaptation"
* #189 "Cure thermale des voies respiratoires"
* #193 "Cure thermale en rhumatologie et séquelles de traumatismes ostéo-articulaires"
* #194 "Cure thermale en dermatologie"
* #195 "Lutte contre les toxicomanies (autres que l'alcoolisme)"
* #196 "Lutte contre l'alcoolisme (y compris alcoologie)"
* #198 "Lutte contre le cancer (activité des CRLC)"
* #206 "Lutte antihansénienne (lèpre)"
* #214 "Postcure pour alcooliques"
* #217 "Lutte contre la tuberculose indifférenciée"
* #219 "Lutte contre la tuberculose pulmonaire (sanatorium pulmonaire, hôtel de cure)"
* #220 "Lutte contre la tuberculose extrapulmonaire"
* #221 "Cure et repos en préventorium"
* #222 "Aérium (traitements préventifs de la tuberculose)"
* #223 "Médecine générale polyvalente"
* #224 "Observation et traitement pneumoconioses"
* #225 "Médecine interne"
* #226 "Accueil et orientation des malades atteints ou suspects de tuberculose pulmonaire"
* #227 "Postcure pour tuberculeux"
* #230 "Psychiatrie générale"
* #235 "Soins intensifs de néonatologie"
* #236 "Psychiatrie infanto-juvénile"
* #252 "Pouponnière à caractère sanitaire (hébergement et soins en )"
* #263 "Placement familial sanitaire"
* #267 "Action médico-sociale précoce pour enfants polyhandicapés"
* #268 "Action médico-sociale précoce pour autre catégorie de clientèle"
* #269 "Soins de type foyer à double tarification pour adultes handicapés"
* #273 "Hébergement en service de soins de longue durée"
* #302 "Chimiothérapie en hématologie et cancérologie"
* #304 "Transplantation du foie"
* #305 "Transplantations rénales"
* #306 "Transplantations cardiaques"
* #309 "Interruption volontaire de grossesse"
* #310 "Examens de santé et bilans"
* #311 "Transplantation coeur-poumon"
* #312 "Néphrologie"
* #313 "Psychiatrie - sorties modifiant la tarification"
* #314 "Allogreffe de moelle osseuse"
* #316 "Autre transplantation d'organe (grêle, poumon, pancréas, multigreffe, ...)"
* #318 "Action médico-sociale précoce pour tous types de déficiences S.A.I"
* #320 "Activités des CMPP"
* #321 "Action médico-sociale précoce pour déficients auditifs"
* #322 "Action médico-sociale précoce pour déficients visuels"
* #323 "Action médico-sociale précoce pour déficients moteurs"
* #324 "Action médico-sociale précoce pour déficients intellectuels"
* #325 "Placement familial spécialisé pour enfants handicapés"
* #355 "Activités des centres de jour pour personnes âgées"
* #358 "Soins à domicile"
* #389 "Lutte contre la stérilité"
* #398 "Placement familial spécialisé pour adultes handicapés"
* #401 "Unité de proximité d'accueil, de traitement et d'orientation des urgences (UPATOU)"
* #402 "Service d'accueil et de traitemet des urgences (SAU)"
* #403 "Pôle spécialisé d'urgence en pédiatrie (POSU)"
* #404 "Pôle spécialisé d'urgence en ophtalmologie (POSU)"
* #405 "Pôle spécialisé d'urgence en cardiologie (POSU)"
* #406 "Pôle spécialisé d'urgence en traumatologie (POSU)"
* #407 "Pôle spécialisé d'urgence en 'SOS main'(POSU)"
* #408 "Pôle spécialisé d'urgence en neurochirgie (POSU)"
* #409 "Autre pôle spécialisé d'urgence non dénommé ailleurs (POSU)"
* #457 "Cure médicale spécialisée contre la tuberculose indifférenciée"
* #458 "Cure médicale spécialisée contre la tuberculose pulmonaire"
* #459 "Cure médicale specialisée contre la tuberculose extra-pulmonaire"
* #460 "Cure médicale spécialisée contre la tuberculose (préventorium)"
* #462 "Autre cure médicale spécialisée pour enfants (notamment aérium reclassé)"
* #463 "Autre cure médicale spécialisée pour tous âges"
* #464 "Cure médicale spécialisée pneumologique pour enfants"
* #465 "Cure médicale spécialisée pneumologique pour tous âges"
* #466 "Convalescence réadaptation pour personnes âgées"
* #467 "Cure médicale spécialisée cardiologique pour enfants"
* #468 "Cure médicale spécialisée cardiologique pour tous âges"
* #552 "Entraînement à l'hémodialyse à domicile et à l'autodialyse"
* #553 "Entraînement à la dialyse péritonéale à domicile"
* #554 "Entraînement à la dialyse péritonéale continue"
* #555 "Dialyse péritonéale"
* #556 "Dialyse péritonéale continue"
* #557 "ORL et stomatologie indifférenciées"
* #588 "Soins courants en établissement d'hébergement pour personnes âgées"
* #593 "Accueil de l'enfant accompagnant la mère convalescente"
* #594 "Repos prénatal"
* #595 "Convalescence postnatale"
* #604 "Cure médicale non spécialisée pour enfants (MECS ouverte en permanence)"
* #605 "Cure médicale non spécialisée pour enfants (MECS ouverte temporairement)"
* #606 "Cure thermale pour enfants (MECS ouverte en permanence)"
* #607 "Cure thermale pour enfants (MECS ouverte de façon temporaire)"
* #608 "Cure médicale pour enfants atteints d'affections chroniques non tuberculeuses des voies respiratoires (MECS ouverte en permanence)"
* #609 "Cure médicale pour enfants atteints d'affections chroniques non tuberculeuses des voies respiratoires (MECS ouverte de façon temporaire)"
* #610 "Cure médicale pour enfants convalescents de rhumatismes aigus (MECS ouverte en permanence)"
* #611 "Cure médicale pour enfants convalescents de rhumatismes aigus (MECS ouverte de façon temporaire)"
* #612 "Cure médicale pour enfants diabétiques (MECS ouverte en permanence)"
* #613 "Cure médicale pour enfants diabétiques (MECS ouverte de façon temporaire)"
* #614 "Cure médicale pour enfants épileptiques (MECS ouverte en permanence)"
* #615 "Cure médicale pour enfants épileptiques (MECS ouverte de façon temporaire)"
* #616 "Cure médicale pour enfants atteints de déficiences temporaires somatopsychologiques (MECS ouverte en permanence)"
* #618 "Cure médicale pour enfants hémophiles (MECS ouverte en permanence)"
* #619 "Cure médicale pour enfants hémophiles (MECS ouverte de façon temporaire)"
* #620 "Cure médicale pour enfants atteints d'infirmités orthopédiques (MECS ouverte en permanence)"
* #621 "Cure médicale pour enfants atteints d'infirmités orthopédiques (MECS ouverte de façon temporaire)"
* #622 "Cure médicale pour enfants énurétiques (MECS ouverte en permanence)"
* #623 "Cure médicale pour enfants énurétiques (MECS ouverte de façon temporaire)"
* #624 "Autre cure médicale spécialisée pour enfants (MECS ouverte en permanence)"
* #625 "Autre cure médicale spécialisée pour enfants (MECS ouverte de façon temporaire)"
* #627 "Moyen séjour indifférencié"
* #628 "Orthopédie"
* #631 "Gynécologie chirurgicale"
* #635 "Réanimation néonatale"
* #636 "Réanimation pédiatrique"
* #637 "Surveillance continue en cardiologie"
* #638 "Surveillance continue en pédiatrie"
* #639 "Surveillance continue en néphrologie"
* #640 "Surveillance continue en urologie"
* #641 "Réanimation en cardiologie"
* #644 "Neutronthérapie"
* #645 "Oxygénothérapie isolée (insuffisants respiratoires)"
* #646 "Assistance ventilatoire sans trachéotomie (insuffisants respiratoires)"
* #647 "Assistance ventilatoire endotrachéale (insuffisants respiratoires)"
* #648 "Trachéotomie isolée (insuffisants respiratoires)"
* #651 "Cure thermale des affections des muqueuses buccolinguales"
* #654 "Hébergement spécialisé pour enfants et adolescents handicapés"
* #657 "Hébergement temporaire pour personnes âgées"
* #663 "Nutrition parentérale pour enfants"
* #664 "Nutrition parentérale pour adultes"
* #715 "Surveillance par monitorage en vue de prévenir la mort subite et inexpliquée du nourrisson"
* #717 "Soins hautement spécialisés en médecine"
* #718 "Soins hautement spécialisés en chirurgie"
* #719 "Soins hautement spécialisés en gynécologie-obstétrique"
* #720 "Réanimation néonatale et pédiatrique indifférenciée"
* #721 "Radiothérapie métabolique (ingestion de source)"
* #722 "Maladies infectieuses, tropicales et exotiques indifférenciées"
* #723 "Autodialyse"
* #728 "Cardiologie infantile"
* #729 "Néphrologie infantile"
* #730 "Carcinologie infantile"
* #731 "Autres spécialités pédiatriques"
* #732 "Hépatologie"
* #733 "Gastro-entérologie"
* #734 "Réanimation chirurgicale pédiatrique"
* #735 "Réanimation chirurgicale adulte"
* #736 "Traumatologie"
* #737 "Convalescence et réadaptation"
* #738 "Rééducation fonctionnelle et réadaptation motrice orientation rhumatologie"
* #739 "Rééducation fonctionnelle et réadaptation motrice orientation traumatologie"
* #743 "Immuno-hématologie"
* #744 "Immuno-cancérologie"
* #753 "Imagerie par résonance magnétique (IRM)"
* #797 "Hémodialyse et hémofiltration pour chroniques adultes"
* #798 "Hémodialyse et hémofiltration pour chroniques enfants"
* #799 "Assistance ventilatoire avec prothèse extrathoracique(insiffisants respiratoires)"
* #800 "Assistance ventilatoire par pression positive continue ou autres techniques particulières agréées (insuffisants respiratoires)"
* #801 "Insulinothérapie"
* #803 "Psychitatrie pour arriérés profonds"
* #806 "Atelier thérapeutique pour adultes"
* #807 "Atelier thérapeutique pour adolescents"
* #808 "Sectorisation psychiatrique en milieu pénitenciaire"
* #809 "Hématologie pédiatrique"
* #825 "Soins et accompagnement des malades en phase terminale-Soins palliatifs"
* #826 "Traitement spécialisé contre la douleur"
* #827 "Nutrition entérale à domicile"
* #828 "Cure thermale pour maladies cardio-artérielles"
* #829 "Cure thermale en neurologie"
* #830 "Cure thermale pour affections psychosomatiques"
* #831 "Cure thermale en phlébologie"
* #832 "Cure thermale pour troubles du développement chez l'enfant"
* #833 "Cure thermale en gynécologie"
* #834 "Cure thermale pour maladies de l'appareil digestif et maladies métaboliques"
* #835 "Cure thermale pour maladies de l'appareil urinaire et maladies métaboliques"
* #897 "Hébergement ouvert en foyer pour adultes handicapés"
* #924 "Hébergement en maison de retraite"
* #925 "Hébergement en logement foyer pour personnes âgées seules (F1)"
* #926 "Hébergement en logement foyer pour personnes âgées en couple (F2)"
* #927 "Hébergement en logement foyer pour personnes âgées"
* #936 "Hébergement en logement foyer pour personnes âgées"
* #939 "Hébergement en logement foyer pour personnes âgées"