CodeSystem: FRCoreCodeSystemDisciplinePrestation
Id: fr-core-cs-discipline-prestation
Title: "FR Core CodeSystem Discipline de prestation - nomenclature SAE"
Description: "La nomenclature des discipline de prestation."
* insert SetCodesystem
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* ^experimental = false


* #35 "Scanographie X" "Scanographie X"
* #39 "Radiothérapie externe (césium, cobalt)" "Radiothérapie externe (césium, cobalt)"
* #43 "Curiethérapie" "Curiethérapie"
* #76 "Immunologie sans autre indication (sai)" "Immunologie sans autre indication (sai)"
* #102 "Maladies infectieuses" "Maladies infectieuses"
* #103 "Toxicologie (y compris en particulier activité des centres antipoison)" "Toxicologie (y compris en particulier activité des centres antipoison)"
* #104 "Réanimation médicale (y compris soins intensifs)" "Réanimation médicale (y compris soins intensifs)"
* #105 "Réanimation polyvalente (médicale + chirurgicale, y compris soins intensifs)" "Réanimation polyvalente (médicale + chirurgicale, y compris soins intensifs)"
* #106 "Surveillance continue - médecine (non compris soins intensifs)" "Surveillance continue - médecine (non compris soins intensifs)"
* #107 "Surveillance continue polyvalente (médicale+chirurgicale, non compris soins intensifs)" "Surveillance continue polyvalente (médicale+chirurgicale, non compris soins intensifs)"
* #108 "Pédiatrie indifférenciée" "Pédiatrie indifférenciée"
* #109 "Pédiatrie enfants et adolescents" "Pédiatrie enfants et adolescents"
* #110 "Pédiatrie nouveau-nés et nourrissons indifférenciée" "Pédiatrie nouveau-nés et nourrissons indifférenciée"
* #111 "Pédiatrie nourrissons" "Pédiatrie nourrissons"
* #112 "Néonatologie" "Néonatologie"
* #113 "Médecine gériatrique" "Médecine gériatrique"
* #114 "Spécialités médicales indifférenciées" "Spécialités médicales indifférenciées"
* #115 "Allergologie" "Allergologie"
* #116 "Dermatologie et vénérologie indifférenciées" "Dermatologie et vénérologie indifférenciées"
* #117 "Dermatologie" "Dermatologie"
* #118 "Vénérologie" "Vénérologie"
* #119 "Endocrinologie, diabétologie, nutrition et métabolisme indifférenciés" "Endocrinologie, diabétologie, nutrition et métabolisme indifférenciés"
* #120 "Endocrinologie" "Endocrinologie"
* #121 "Diabétologie" "Diabétologie"
* #122 "Nutrition-métabolisme" "Nutrition-métabolisme"
* #123 "Hématologie et maladies du sang" "Hématologie et maladies du sang"
* #124 "Hépatogastro-entérologie" "Hépatogastro-entérologie"
* #125 "Maladies tropicales et exotiques" "Maladies tropicales et exotiques"
* #126 "Médecine carcinologique" "Médecine carcinologique"
* #127 "Médecine cardiovasculaire" "Médecine cardiovasculaire"
* #129 "Neurologie" "Neurologie"
* #130 "Pneumologie indifférenciée" "Pneumologie indifférenciée"
* #131 "Pneumologie non tuberculeuse" "Pneumologie non tuberculeuse"
* #132 "Phtisiologie" "Phtisiologie"
* #133 "Rhumatologie" "Rhumatologie"
* #134 "Radiothérapie et médecine nucléaire indifférenciées" "Radiothérapie et médecine nucléaire indifférenciées"
* #135 "Radiothérapie" "Radiothérapie"
* #136 "Médecine nucléaire" "Médecine nucléaire"
* #137 "Chirurgie générale" "Chirurgie générale"
* #138 "Chirurgie infantile indifférenciée" "Chirurgie infantile indifférenciée"
* #139 "Chirurgie enfants et adolescents" "Chirurgie enfants et adolescents"
* #140 "Chirurgie nouveau-nés et nourrissons" "Chirurgie nouveau-nés et nourrissons"
* #141 "Réanimation chirurgicale indifférenciée (y compris soins intensifs)" "Réanimation chirurgicale indifférenciée (y compris soins intensifs)"
* #142 "Surveillance continue chirurgicale (non compris soins intensifs)" "Surveillance continue chirurgicale (non compris soins intensifs)"
* #143 "Spécialités chirurgicales indifférenciées" "Spécialités chirurgicales indifférenciées"
* #144 "Chirurgie carcinologique" "Chirurgie carcinologique"
* #145 "Chirurgie des grands brûlés" "Chirurgie des grands brûlés"
* #146 "Chirurgie digestive" "Chirurgie digestive"
* #147 "Chirurgie thoracique et cardiovasculaire indiférenciée" "Chirurgie thoracique et cardiovasculaire indiférenciée"
* #148 "Chirurgie thoracopulmonaire" "Chirurgie thoracopulmonaire"
* #149 "Chirurgie vasculaire" "Chirurgie vasculaire"
* #150 "Chirurgie cardiovasculaire" "Chirurgie cardiovasculaire"
* #151 "Neurochirurgie" "Neurochirurgie"
* #152 "Orthopédie-traumatologie et chirurgie plastique et réparatrice indifférenciées" "Orthopédie-traumatologie et chirurgie plastique et réparatrice indifférenciées"
* #153 "Orthopédie-traumatologie" "Orthopédie-traumatologie"
* #154 "Chirurgie plastique et réparatrice" "Chirurgie plastique et réparatrice"
* #155 "ORL et ophtalmologie indifférenciées" "ORL et ophtalmologie indifférenciées"
* #156 "ORL" "ORL"
* #157 "Ophtalmologie" "Ophtalmologie"
* #158 "Stomatologie et chirurgie maxillofaciale indifférenciées" "Stomatologie et chirurgie maxillofaciale indifférenciées"
* #159 "Stomatologie" "Stomatologie"
* #160 "Chirurgie maxillofaciale" "Chirurgie maxillofaciale"
* #161 "Urologie" "Urologie"
* #162 "ORL, ophtalmologie et stomatologie indifférenciées" "ORL, ophtalmologie et stomatologie indifférenciées"
* #163 "Gynécologie et obstétrique indifférenciées" "Gynécologie et obstétrique indifférenciées"
* #164 "Gynécologie" "Gynécologie"
* #165 "Obstétrique" "Obstétrique"
* #166 "Chroniques et convalescents indifférenciés" "Chroniques et convalescents indifférenciés"
* #167 "Chroniques" "Chroniques"
* #168 "Repos, convalescence et régime indifférenciés" "Repos, convalescence et régime indifférenciés"
* #169 "Repos" "Repos"
* #170 "Convalescence" "Convalescence"
* #171 "Régime (y compris diététique)" "Régime (y compris diététique)"
* #172 "Rééducation fonctionnelle et réadaptation polyvalente" "Rééducation fonctionnelle et réadaptation polyvalente"
* #173 "Cure thermale indifférenciée" "Cure thermale indifférenciée"
* #174 "Médecine générale et spécialités médicales indifférenciées" "Médecine générale et spécialités médicales indifférenciées"
* #176 "Long séjour pour personnes ayant perdu leur autonomie de vie" "Long séjour pour personnes ayant perdu leur autonomie de vie"
* #177 "Cure médicale en établissement d'hébergements pour personnes âgées" "Cure médicale en établissement d'hébergements pour personnes âgées"
* #178 "Rééducation fonctionnelle et réadaptation motrice indifférenciée" "Rééducation fonctionnelle et réadaptation motrice indifférenciée"
* #179 "Rééducation fonctionnelle et réadaptation neurologique" "Rééducation fonctionnelle et réadaptation neurologique"
* #180 "Rééducation des affections respiratoires" "Rééducation des affections respiratoires"
* #181 "Chirurgie générale et spécialités chirugicales indifférenciées" "Chirurgie générale et spécialités chirugicales indifférenciées"
* #182 "Rééducation des maladies cardiovasculaires" "Rééducation des maladies cardiovasculaires"
* #183 "Obstétrique sans possibilités chirurgicales" "Obstétrique sans possibilités chirurgicales"
* #184 "Rééducation des affections hépatodigestives" "Rééducation des affections hépatodigestives"
* #185 "Repos et convalescence indifférenciés" "Repos et convalescence indifférenciés"
* #187 "Autre rééducation fonctionnelle et réadaptation" "Autre rééducation fonctionnelle et réadaptation"
* #189 "Cure thermale des voies respiratoires" "Cure thermale des voies respiratoires"
* #193 "Cure thermale en rhumatologie et séquelles de traumatismes ostéo-articulaires" "Cure thermale en rhumatologie et séquelles de traumatismes ostéo-articulaires"
* #194 "Cure thermale en dermatologie" "Cure thermale en dermatologie"
* #195 "Lutte contre les toxicomanies (autres que l'alcoolisme)" "Lutte contre les toxicomanies (autres que l'alcoolisme)"
* #196 "Lutte contre l'alcoolisme (y compris alcoologie)" "Lutte contre l'alcoolisme (y compris alcoologie)"
* #198 "Lutte contre le cancer (activité des CRLC)" "Lutte contre le cancer (activité des CRLC)"
* #206 "Lutte antihansénienne (lèpre)" "Lutte antihansénienne (lèpre)"
* #214 "Postcure pour alcooliques" "Postcure pour alcooliques"
* #217 "Lutte contre la tuberculose indifférenciée" "Lutte contre la tuberculose indifférenciée"
* #219 "Lutte contre la tuberculose pulmonaire (sanatorium pulmonaire, hôtel de cure)" "Lutte contre la tuberculose pulmonaire (sanatorium pulmonaire, hôtel de cure)"
* #220 "Lutte contre la tuberculose extrapulmonaire" "Lutte contre la tuberculose extrapulmonaire"
* #221 "Cure et repos en préventorium" "Cure et repos en préventorium"
* #222 "Aérium (traitements préventifs de la tuberculose)" "Aérium (traitements préventifs de la tuberculose)"
* #223 "Médecine générale polyvalente" "Médecine générale polyvalente"
* #224 "Observation et traitement pneumoconioses" "Observation et traitement pneumoconioses"
* #225 "Médecine interne" "Médecine interne"
* #226 "Accueil et orientation des malades atteints ou suspects de tuberculose pulmonaire" "Accueil et orientation des malades atteints ou suspects de tuberculose pulmonaire"
* #227 "Postcure pour tuberculeux" "Postcure pour tuberculeux"
* #230 "Psychiatrie générale" "Psychiatrie générale"
* #235 "Soins intensifs de néonatologie" "Soins intensifs de néonatologie"
* #236 "Psychiatrie infanto-juvénile" "Psychiatrie infanto-juvénile"
* #252 "Pouponnière à caractère sanitaire (hébergement et soins en )" "Pouponnière à caractère sanitaire (hébergement et soins en )"
* #263 "Placement familial sanitaire" "Placement familial sanitaire"
* #267 "Action médico-sociale précoce pour enfants polyhandicapés" "Action médico-sociale précoce pour enfants polyhandicapés"
* #268 "Action médico-sociale précoce pour autre catégorie de clientèle" "Action médico-sociale précoce pour autre catégorie de clientèle"
* #269 "Soins de type foyer à double tarification pour adultes handicapés" "Soins de type foyer à double tarification pour adultes handicapés"
* #273 "Hébergement en service de soins de longue durée" "Hébergement en service de soins de longue durée"
* #302 "Chimiothérapie en hématologie et cancérologie" "Chimiothérapie en hématologie et cancérologie"
* #304 "Transplantation du foie" "Transplantation du foie"
* #305 "Transplantations rénales" "Transplantations rénales"
* #306 "Transplantations cardiaques" "Transplantations cardiaques"
* #309 "Interruption volontaire de grossesse" "Interruption volontaire de grossesse"
* #310 "Examens de santé et bilans" "Examens de santé et bilans"
* #311 "Transplantation coeur-poumon" "Transplantation coeur-poumon"
* #312 "Néphrologie" "Néphrologie"
* #313 "Psychiatrie - sorties modifiant la tarification" "Psychiatrie - sorties modifiant la tarification"
* #314 "Allogreffe de moelle osseuse" "Allogreffe de moelle osseuse"
* #316 "Autre transplantation d'organe (grêle, poumon, pancréas, multigreffe, ...)" "Autre transplantation d'organe (grêle, poumon, pancréas, multigreffe, ...)"
* #318 "Action médico-sociale précoce pour tous types de déficiences S.A.I" "Action médico-sociale précoce pour tous types de déficiences S.A.I"
* #320 "Activités des CMPP" "Activités des CMPP"
* #321 "Action médico-sociale précoce pour déficients auditifs" "Action médico-sociale précoce pour déficients auditifs"
* #322 "Action médico-sociale précoce pour déficients visuels" "Action médico-sociale précoce pour déficients visuels"
* #323 "Action médico-sociale précoce pour déficients moteurs" "Action médico-sociale précoce pour déficients moteurs"
* #324 "Action médico-sociale précoce pour déficients intellectuels" "Action médico-sociale précoce pour déficients intellectuels"
* #325 "Placement familial spécialisé pour enfants handicapés" "Placement familial spécialisé pour enfants handicapés"
* #355 "Activités des centres de jour pour personnes âgées" "Activités des centres de jour pour personnes âgées"
* #358 "Soins à domicile" "Soins à domicile"
* #389 "Lutte contre la stérilité" "Lutte contre la stérilité"
* #398 "Placement familial spécialisé pour adultes handicapés" "Placement familial spécialisé pour adultes handicapés"
* #401 "Unité de proximité d'accueil, de traitement et d'orientation des urgences (UPATOU)" "Unité de proximité d'accueil, de traitement et d'orientation des urgences (UPATOU)"
* #402 "Service d'accueil et de traitemet des urgences (SAU)" "Service d'accueil et de traitemet des urgences (SAU)"
* #403 "Pôle spécialisé d'urgence en pédiatrie (POSU)" "Pôle spécialisé d'urgence en pédiatrie (POSU)"
* #404 "Pôle spécialisé d'urgence en ophtalmologie (POSU)" "Pôle spécialisé d'urgence en ophtalmologie (POSU)"
* #405 "Pôle spécialisé d'urgence en cardiologie (POSU)" "Pôle spécialisé d'urgence en cardiologie (POSU)"
* #406 "Pôle spécialisé d'urgence en traumatologie (POSU)" "Pôle spécialisé d'urgence en traumatologie (POSU)"
* #407 "Pôle spécialisé d'urgence en 'SOS main'(POSU)" "Pôle spécialisé d'urgence en 'SOS main'(POSU)"
* #408 "Pôle spécialisé d'urgence en neurochirgie (POSU)" "Pôle spécialisé d'urgence en neurochirgie (POSU)"
* #409 "Autre pôle spécialisé d'urgence non dénommé ailleurs (POSU)" "Autre pôle spécialisé d'urgence non dénommé ailleurs (POSU)"
* #457 "Cure médicale spécialisée contre la tuberculose indifférenciée" "Cure médicale spécialisée contre la tuberculose indifférenciée"
* #458 "Cure médicale spécialisée contre la tuberculose pulmonaire" "Cure médicale spécialisée contre la tuberculose pulmonaire"
* #459 "Cure médicale specialisée contre la tuberculose extra-pulmonaire" "Cure médicale specialisée contre la tuberculose extra-pulmonaire"
* #460 "Cure médicale spécialisée contre la tuberculose (préventorium)" "Cure médicale spécialisée contre la tuberculose (préventorium)"
* #462 "Autre cure médicale spécialisée pour enfants (notamment aérium reclassé)" "Autre cure médicale spécialisée pour enfants (notamment aérium reclassé)"
* #463 "Autre cure médicale spécialisée pour tous âges" "Autre cure médicale spécialisée pour tous âges"
* #464 "Cure médicale spécialisée pneumologique pour enfants" "Cure médicale spécialisée pneumologique pour enfants"
* #465 "Cure médicale spécialisée pneumologique pour tous âges" "Cure médicale spécialisée pneumologique pour tous âges"
* #466 "Convalescence réadaptation pour personnes âgées" "Convalescence réadaptation pour personnes âgées"
* #467 "Cure médicale spécialisée cardiologique pour enfants" "Cure médicale spécialisée cardiologique pour enfants"
* #468 "Cure médicale spécialisée cardiologique pour tous âges" "Cure médicale spécialisée cardiologique pour tous âges"
* #552 "Entraînement à l'hémodialyse à domicile et à l'autodialyse" "Entraînement à l'hémodialyse à domicile et à l'autodialyse"
* #553 "Entraînement à la dialyse péritonéale à domicile" "Entraînement à la dialyse péritonéale à domicile"
* #554 "Entraînement à la dialyse péritonéale continue" "Entraînement à la dialyse péritonéale continue"
* #555 "Dialyse péritonéale" "Dialyse péritonéale"
* #556 "Dialyse péritonéale continue" "Dialyse péritonéale continue"
* #557 "ORL et stomatologie indifférenciées" "ORL et stomatologie indifférenciées"
* #588 "Soins courants en établissement d'hébergement pour personnes âgées" "Soins courants en établissement d'hébergement pour personnes âgées"
* #593 "Accueil de l'enfant accompagnant la mère convalescente" "Accueil de l'enfant accompagnant la mère convalescente"
* #594 "Repos prénatal" "Repos prénatal"
* #595 "Convalescence postnatale" "Convalescence postnatale"
* #604 "Cure médicale non spécialisée pour enfants (MECS ouverte en permanence)" "Cure médicale non spécialisée pour enfants (MECS ouverte en permanence)"
* #605 "Cure médicale non spécialisée pour enfants (MECS ouverte temporairement)" "Cure médicale non spécialisée pour enfants (MECS ouverte temporairement)"
* #606 "Cure thermale pour enfants (MECS ouverte en permanence)" "Cure thermale pour enfants (MECS ouverte en permanence)"
* #607 "Cure thermale pour enfants (MECS ouverte de façon temporaire)" "Cure thermale pour enfants (MECS ouverte de façon temporaire)"
* #608 "Cure médicale pour enfants atteints d'affections chroniques non tuberculeuses des voies respiratoires (MECS ouverte en permanence)" "Cure médicale pour enfants atteints d'affections chroniques non tuberculeuses des voies respiratoires (MECS ouverte en permanence)"
* #609 "Cure médicale pour enfants atteints d'affections chroniques non tuberculeuses des voies respiratoires (MECS ouverte de façon temporaire)" "Cure médicale pour enfants atteints d'affections chroniques non tuberculeuses des voies respiratoires (MECS ouverte de façon temporaire)"
* #610 "Cure médicale pour enfants convalescents de rhumatismes aigus (MECS ouverte en permanence)" "Cure médicale pour enfants convalescents de rhumatismes aigus (MECS ouverte en permanence)"
* #611 "Cure médicale pour enfants convalescents de rhumatismes aigus (MECS ouverte de façon temporaire)" "Cure médicale pour enfants convalescents de rhumatismes aigus (MECS ouverte de façon temporaire)"
* #612 "Cure médicale pour enfants diabétiques (MECS ouverte en permanence)" "Cure médicale pour enfants diabétiques (MECS ouverte en permanence)"
* #613 "Cure médicale pour enfants diabétiques (MECS ouverte de façon temporaire)" "Cure médicale pour enfants diabétiques (MECS ouverte de façon temporaire)"
* #614 "Cure médicale pour enfants épileptiques (MECS ouverte en permanence)" "Cure médicale pour enfants épileptiques (MECS ouverte en permanence)"
* #615 "Cure médicale pour enfants épileptiques (MECS ouverte de façon temporaire)" "Cure médicale pour enfants épileptiques (MECS ouverte de façon temporaire)"
* #616 "Cure médicale pour enfants atteints de déficiences temporaires somatopsychologiques (MECS ouverte en permanence)" "Cure médicale pour enfants atteints de déficiences temporaires somatopsychologiques (MECS ouverte en permanence)"
* #618 "Cure médicale pour enfants hémophiles (MECS ouverte en permanence)" "Cure médicale pour enfants hémophiles (MECS ouverte en permanence)"
* #619 "Cure médicale pour enfants hémophiles (MECS ouverte de façon temporaire)" "Cure médicale pour enfants hémophiles (MECS ouverte de façon temporaire)"
* #620 "Cure médicale pour enfants atteints d'infirmités orthopédiques (MECS ouverte en permanence)" "Cure médicale pour enfants atteints d'infirmités orthopédiques (MECS ouverte en permanence)"
* #621 "Cure médicale pour enfants atteints d'infirmités orthopédiques (MECS ouverte de façon temporaire)" "Cure médicale pour enfants atteints d'infirmités orthopédiques (MECS ouverte de façon temporaire)"
* #622 "Cure médicale pour enfants énurétiques (MECS ouverte en permanence)" "Cure médicale pour enfants énurétiques (MECS ouverte en permanence)"
* #623 "Cure médicale pour enfants énurétiques (MECS ouverte de façon temporaire)" "Cure médicale pour enfants énurétiques (MECS ouverte de façon temporaire)"
* #624 "Autre cure médicale spécialisée pour enfants (MECS ouverte en permanence)" "Autre cure médicale spécialisée pour enfants (MECS ouverte en permanence)"
* #625 "Autre cure médicale spécialisée pour enfants (MECS ouverte de façon temporaire)" "Autre cure médicale spécialisée pour enfants (MECS ouverte de façon temporaire)"
* #627 "Moyen séjour indifférencié" "Moyen séjour indifférencié"
* #628 "Orthopédie" "Orthopédie"
* #631 "Gynécologie chirurgicale" "Gynécologie chirurgicale"
* #635 "Réanimation néonatale" "Réanimation néonatale"
* #636 "Réanimation pédiatrique" "Réanimation pédiatrique"
* #637 "Surveillance continue en cardiologie" "Surveillance continue en cardiologie"
* #638 "Surveillance continue en pédiatrie" "Surveillance continue en pédiatrie"
* #639 "Surveillance continue en néphrologie" "Surveillance continue en néphrologie"
* #640 "Surveillance continue en urologie" "Surveillance continue en urologie"
* #641 "Réanimation en cardiologie" "Réanimation en cardiologie"
* #644 "Neutronthérapie" "Neutronthérapie"
* #645 "Oxygénothérapie isolée (insuffisants respiratoires)" "Oxygénothérapie isolée (insuffisants respiratoires)"
* #646 "Assistance ventilatoire sans trachéotomie (insuffisants respiratoires)" "Assistance ventilatoire sans trachéotomie (insuffisants respiratoires)"
* #647 "Assistance ventilatoire endotrachéale (insuffisants respiratoires)" "Assistance ventilatoire endotrachéale (insuffisants respiratoires)"
* #648 "Trachéotomie isolée (insuffisants respiratoires)" "Trachéotomie isolée (insuffisants respiratoires)"
* #651 "Cure thermale des affections des muqueuses buccolinguales" "Cure thermale des affections des muqueuses buccolinguales"
* #654 "Hébergement spécialisé pour enfants et adolescents handicapés" "Hébergement spécialisé pour enfants et adolescents handicapés"
* #657 "Hébergement temporaire pour personnes âgées" "Hébergement temporaire pour personnes âgées"
* #663 "Nutrition parentérale pour enfants" "Nutrition parentérale pour enfants"
* #664 "Nutrition parentérale pour adultes" "Nutrition parentérale pour adultes"
* #715 "Surveillance par monitorage en vue de prévenir la mort subite et inexpliquée du nourrisson" "Surveillance par monitorage en vue de prévenir la mort subite et inexpliquée du nourrisson"
* #717 "Soins hautement spécialisés en médecine" "Soins hautement spécialisés en médecine"
* #718 "Soins hautement spécialisés en chirurgie" "Soins hautement spécialisés en chirurgie"
* #719 "Soins hautement spécialisés en gynécologie-obstétrique" "Soins hautement spécialisés en gynécologie-obstétrique"
* #720 "Réanimation néonatale et pédiatrique indifférenciée" "Réanimation néonatale et pédiatrique indifférenciée"
* #721 "Radiothérapie métabolique (ingestion de source)" "Radiothérapie métabolique (ingestion de source)"
* #722 "Maladies infectieuses, tropicales et exotiques indifférenciées" "Maladies infectieuses, tropicales et exotiques indifférenciées"
* #723 "Autodialyse" "Autodialyse"
* #728 "Cardiologie infantile" "Cardiologie infantile"
* #729 "Néphrologie infantile" "Néphrologie infantile"
* #730 "Carcinologie infantile" "Carcinologie infantile"
* #731 "Autres spécialités pédiatriques" "Autres spécialités pédiatriques"
* #732 "Hépatologie" "Hépatologie"
* #733 "Gastro-entérologie" "Gastro-entérologie"
* #734 "Réanimation chirurgicale pédiatrique" "Réanimation chirurgicale pédiatrique"
* #735 "Réanimation chirurgicale adulte" "Réanimation chirurgicale adulte"
* #736 "Traumatologie" "Traumatologie"
* #737 "Convalescence et réadaptation" "Convalescence et réadaptation"
* #738 "Rééducation fonctionnelle et réadaptation motrice orientation rhumatologie" "Rééducation fonctionnelle et réadaptation motrice orientation rhumatologie"
* #739 "Rééducation fonctionnelle et réadaptation motrice orientation traumatologie" "Rééducation fonctionnelle et réadaptation motrice orientation traumatologie"
* #743 "Immuno-hématologie" "Immuno-hématologie"
* #744 "Immuno-cancérologie" "Immuno-cancérologie"
* #753 "Imagerie par résonance magnétique (IRM)" "Imagerie par résonance magnétique (IRM)"
* #797 "Hémodialyse et hémofiltration pour chroniques adultes" "Hémodialyse et hémofiltration pour chroniques adultes"
* #798 "Hémodialyse et hémofiltration pour chroniques enfants" "Hémodialyse et hémofiltration pour chroniques enfants"
* #799 "Assistance ventilatoire avec prothèse extrathoracique(insiffisants respiratoires)" "Assistance ventilatoire avec prothèse extrathoracique(insiffisants respiratoires)"
* #800 "Assistance ventilatoire par pression positive continue ou autres techniques particulières agréées (insuffisants respiratoires)" "Assistance ventilatoire par pression positive continue ou autres techniques particulières agréées (insuffisants respiratoires)"
* #801 "Insulinothérapie" "Insulinothérapie"
* #803 "Psychitatrie pour arriérés profonds" "Psychitatrie pour arriérés profonds"
* #806 "Atelier thérapeutique pour adultes" "Atelier thérapeutique pour adultes"
* #807 "Atelier thérapeutique pour adolescents" "Atelier thérapeutique pour adolescents"
* #808 "Sectorisation psychiatrique en milieu pénitenciaire" "Sectorisation psychiatrique en milieu pénitenciaire"
* #809 "Hématologie pédiatrique" "Hématologie pédiatrique"
* #825 "Soins et accompagnement des malades en phase terminale-Soins palliatifs" "Soins et accompagnement des malades en phase terminale-Soins palliatifs"
* #826 "Traitement spécialisé contre la douleur" "Traitement spécialisé contre la douleur"
* #827 "Nutrition entérale à domicile" "Nutrition entérale à domicile"
* #828 "Cure thermale pour maladies cardio-artérielles" "Cure thermale pour maladies cardio-artérielles"
* #829 "Cure thermale en neurologie" "Cure thermale en neurologie"
* #830 "Cure thermale pour affections psychosomatiques" "Cure thermale pour affections psychosomatiques"
* #831 "Cure thermale en phlébologie" "Cure thermale en phlébologie"
* #832 "Cure thermale pour troubles du développement chez l'enfant" "Cure thermale pour troubles du développement chez l'enfant"
* #833 "Cure thermale en gynécologie" "Cure thermale en gynécologie"
* #834 "Cure thermale pour maladies de l'appareil digestif et maladies métaboliques" "Cure thermale pour maladies de l'appareil digestif et maladies métaboliques"
* #835 "Cure thermale pour maladies de l'appareil urinaire et maladies métaboliques" "Cure thermale pour maladies de l'appareil urinaire et maladies métaboliques"
* #897 "Hébergement ouvert en foyer pour adultes handicapés" "Hébergement ouvert en foyer pour adultes handicapés"
* #924 "Hébergement en maison de retraite" "Hébergement en maison de retraite"
* #925 "Hébergement en logement foyer pour personnes âgées seules (F1)" "Hébergement en logement foyer pour personnes âgées seules (F1)"
* #926 "Hébergement en logement foyer pour personnes âgées en couple (F2)" "Hébergement en logement foyer pour personnes âgées en couple (F2)"
* #927 "Hébergement en logement foyer pour personnes âgées" "Hébergement en logement foyer pour personnes âgées"
* #936 "Hébergement en logement foyer pour personnes âgées" "Hébergement en logement foyer pour personnes âgées"
* #939 "Hébergement en logement foyer pour personnes âgées" "Hébergement en logement foyer pour personnes âgées"